name: Django CI

on:
  push:
    branches: [ "main" ]
  

jobs:
  build:

    runs-on: ubuntu-latest
    environment: serverubu
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Deploy to VPS
      uses:  appleboy/ssh-action@v1.0.3
      with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASS }}
          port: 22
          script: | 
            cd dev 
            cd portafolio
            git pull
            sudo supervisorctl restart porafolio
            echo "Nice Job!!!"
            exit
